---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-warpper-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-warpper-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: helm-warpper-sa
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-warpper-configmap
  labels:
    app: helm-warpper
data:
  config: |
    uploadPath: /tmp/charts
    helmRepos:
      - name: xuanji
        url: http://chartmuseum-chartmuseum.default.svc.cluster.local:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-warpper
  name: helm-warpper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-warpper
  template:
    metadata:
      labels:
        app: helm-warpper
    spec:
      serviceAccount: helm-warpper-sa
      volumes:
          - name: warpper-config
            configMap:
              name: helm-warpper-configmap
              items: 
                - key: config
                  path: helm-warpper-config.yaml
      containers:
        - image: duccnzj/helm:v5
          imagePullPolicy: IfNotPresent
          name: app
          volumeMounts:
              - name: warpper-config
                mountPath: /config
          command:
              - "/app"
              - "--config=/config/helm-warpper-config.yaml"
              - "--port=80"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-warpper
  name: helm-warpper-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
      nodePort: 32200
  selector:
    app: helm-warpper
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: helm-warpper
  name: helm-warpper-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: api-helm.dev.whoops-cn.club
      http:
        paths:
          - backend:
              serviceName: helm-warpper-service
              servicePort: 8080
            path: /
  tls:
  - hosts:
    - api-helm.dev.whoops-cn.club
    secretName: api-helm-secret