apiVersion: v1
kind: ConfigMap
metadata:
  name: xuanji-configmap
  labels:
    app: xuanji
data:
  xuanji: |
    <?php

    return [
        'deploy_configs' => [
            'project_group' => 'duccnzj',
            'repos'         => [
                [
                    'project'    => 21246576,
                    'file'       => '.env.testing',
                    'repository' => 'duc/sso',
                    'tag'        => fn ($branch, $commit) => 'v2',
                    'chart'      => 'xuanji/sso-chart',
                    'set'        => [
                        'redis.enabled=true',
                        'redis.cluster.slaveCount=0',
                        'redis.usePassword=false',
                        'service.type=NodePort',
                    ],
                ],
            ],
        ],
    ];


  env: |
    APP_NAME=玄机
    APP_ENV=local
    APP_KEY=base64:Lfv97LJROI10OXPQUsS7tfuujiaJRJU1Xz7HhjsXrn8=
    APP_DEBUG=true
    # APP_URL=http://xuanji.work

    LOG_CHANNEL=stderr

    DB_CONNECTION=mysql
    DB_HOST=192.168.199.190
    DB_PORT=3306
    DB_DATABASE=xuanji
    DB_USERNAME=root
    DB_PASSWORD=

    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    REDIS_HOST=127.0.0.1
    REDIS_PASSWORD=null
    REDIS_PORT=6379

    MAIL_MAILER=smtp
    MAIL_HOST=smtp.mailtrap.io
    MAIL_PORT=2525
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null
    MAIL_FROM_ADDRESS=null
    MAIL_FROM_NAME="${APP_NAME}"

    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_DEFAULT_REGION=us-east-1
    AWS_BUCKET=

    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
    PUSHER_APP_CLUSTER=mt1

    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"


    SSO_ENABLED=false

    SSO_PROJECT_NAME=xuanji
    SSO_BASE_URL=http://sso.local:8888/
    SSO_LOGOUT_URL=api/logout

    GITLAB_URL=https://gitlab.com/
    GITLAB_TOKEN=NsrHhzmzwA1MpS5MPWwn

    HELM_API_BASE_URL=http://helm-warpper-service.default.svc.cluster.local:8080

    MIX_SHELL_SOCKET_URL=http://terminal.xuanji.local
    MIX_NS_PREFIX=devops-

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xuanji
    group: xuanji
  name: xuanji
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xuanji
  template:
    metadata:
      labels:
        app: xuanji
    spec:
      volumes:
          - name: env
            configMap:
              name: xuanji-configmap
              items: 
                - key: env
                  path: .env
          - name: xuanji
            configMap:
              name: xuanji-configmap
              items: 
                - key: xuanji
                  path: xuanji.php
      containers:
        - image: duc/xuanji:v5
          imagePullPolicy: IfNotPresent
          name: app
          volumeMounts:
              - mountPath: /var/www/html/.env
                name: env
                subPath: .env
              - mountPath: /var/www/html/config/xuanji.php
                name: xuanji
                subPath: xuanji.php
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    group: xuanji
  name: xuanji-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
      nodePort: 32300
  selector:
    app: xuanji
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    group: xuanji
  name: xuanji-ingress
spec:
  rules:
    - host: web.xuanji.local
      http:
        paths:
          - backend:
              serviceName: xuanji-service
              servicePort: http
            path: /
  # tls:
  # - hosts:
  #   - ingress.k8s.local
  #   secretName: tls-secret
# ---
