apiVersion: v1
kind: ConfigMap
metadata:
  name: xuanji-configmap
  labels:
    app: xuanji
data:
  xuanji: |
    <?php

    return [
        'deploy_configs' => [
            'project_group' => 'duccnzj',
            'repos'         => [
                [
                    'project'    => 21246576,
                    'file'       => '.env.testing',
                    'repository' => 'duccnzj/sso',
                    'tag'        => fn ($branch, $commit) => 'v2',
                    'chart'      => 'xuanji/sso-chart',
                    'set'        => [
                        'redis.enabled=true',
                        'redis.cluster.slaveCount=0',
                        'redis.usePassword=false',
                        'service.type=NodePort',
                    ],
                ],
            ],
        ],
    ];


  env: |
    APP_NAME=玄机
    APP_ENV=local
    APP_KEY=base64:Lfv97LJROI10OXPQUsS7tfuujiaJRJU1Xz7HhjsXrn8=
    APP_DEBUG=true
    # APP_URL=http://xuanji.work

    LOG_CHANNEL=stderr

    DB_CONNECTION=mysql
    DB_HOST=mysql
    DB_PORT=3306
    DB_DATABASE=xuanji
    DB_USERNAME=duc
    DB_PASSWORD=12345

    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    SSO_ENABLED=false

    GITLAB_URL=https://gitlab.com/
    GITLAB_TOKEN=NsrHhzmzwA1MpS5MPWwn

    K8S_CLUSTER_URL=https://47.98.135.180:6443
    K8S_BEARER_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6InJjM1NIU1o2SHUxVlNLXzQtWW0wOGx5bDRZc3g4ekpnQTdBNzJDWDQ5UHcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImhlbG0td2FycHBlci1zYS10b2tlbi14czRxNiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJoZWxtLXdhcnBwZXItc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI2YmQwZDcwYS02NTdhLTQ4M2EtYjEwYS1jNTRlY2QxNTg0OTgiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpoZWxtLXdhcnBwZXItc2EifQ.W2YIAmGyh5FAKHRwH70YDd6KIe7rMAJ_6I15MYGify8eD5Njrq-bEbjRne1aBi23dRng4IMudrhG6AyHH4vO4wGhTz8sKUGeItMylIklwIf8M7zCkwBTa0UuvLOpxGTZqZcWgfTRLe-f_zf1HLDQv53ZUa6OzZ--9S2N2Ce344N-HdjLItC4bXj8TVH-wbsih-bB7fg4MCvXfG9CgLrto6yclasGhetm0Eyi5Qr5TWW4bgfkgHkkadgM88aIkTqHl3B0REq_EOhpB5zx_Z_QrbKBCeoCPaOGoHrgSnIUU3QgVhuWHtWk-NxEKsPq2AWntej0l9wDTsm6eLKgbpgTrg

    HELM_API_BASE_URL=http://helm-warpper-service.default.svc.cluster.local:8080

    MIX_SHELL_SOCKET_URL=https://terminal.dev.whoops-cn.club
    MIX_NS_PREFIX=devops-

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xuanji
    group: xuanji
  name: xuanji
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xuanji
  template:
    metadata:
      labels:
        app: xuanji
    spec:
      volumes:
          - name: env
            configMap:
              name: xuanji-configmap
              items: 
                - key: env
                  path: .env
          - name: xuanji
            configMap:
              name: xuanji-configmap
              items: 
                - key: xuanji
                  path: xuanji.php
      containers:
        - image: duccnzj/xuanji:v4
          imagePullPolicy: IfNotPresent
          name: app
          volumeMounts:
              - mountPath: /var/www/html/.env
                name: env
                subPath: .env
              - mountPath: /var/www/html/config/xuanji.php
                name: xuanji
                subPath: xuanji.php
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    group: xuanji
  name: xuanji-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
      nodePort: 32300
  selector:
    app: xuanji
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    group: xuanji
  name: xuanji-ingress
spec:
  rules:
    - host: xuanji.dev.whoops-cn.club
      http:
        paths:
          - backend:
              serviceName: xuanji-service
              servicePort: http
            path: /
  tls:
  - hosts:
    - xuanji.dev.whoops-cn.club
    secretName: xuanji-secret
